### ISSUE TITLE
Implement "when a Wikibase User removes a statement then it will not be added again"

### ISSUE THREAD

**Issue by D063520** [the-qa-company/WikibaseSync#14]
Currently WikibaseSync implements the functionality that
"when a Wikibase User adds a statement then it will not be deleted"
we need to implement also
"when a Wikibase User removes a statement then it will not be added again"

**Comment by mezez** [comment]
New commit pushed on this

**Comment by D063520** [comment]
The issue should not be closed before it is merged to master

**Comment by madewild** [comment]
where are we with this? it still happened on 9 March on https://linkedopendata.eu/w/index.php?title=Item:Q1&action=history
