### ISSUE TITLE
`sudo` for Windows PC?

### ISSUE THREAD

**Issue by ugochimobi** [the-qa-company/WikibaseSync#17]
Hi, I just want to ask, can this be used with a Windows PC? As much as I know, I don't think Windows understands this `sudo` command. However, I tried using Ubuntu but all the packages that I tried to install failed, throwing an `Unable to fetch package` error.

Any way to handle this?
I appreciate your anticipated response.

**Comment by D063520** [comment]
Hi, 

it is a python project, so yes it can run on any platform. The general idea is to install the python dependencies and run the script.  Maybe this link can help:

https://mothergeo-py.readthedocs.io/en/latest/development/how-to/venv-win.html

The instructions are more for a linux distribution. For the "Unable to fetch package" maybe you can do

`sudo apt-get update`

before. It might fix your problem.

Salut
D063520

**Comment by ugochimobi** [comment]
> Hi,
> 
> it is a python project, so yes it can run on any platform. The general idea is to install the python dependencies and run the script. Maybe this link can help:
> 
> https://mothergeo-py.readthedocs.io/en/latest/development/how-to/venv-win.html
> 
> The instructions are more for a linux distribution. For the "Unable to fetch package" maybe you can do
> 
> `sudo apt-get update`
> 
> before. It might fix your problem.
> 
> Salut D063520

Oh, right, thanks!
Indeed, the instructions are more linux-based than windows; but I think I tried using that `sudo apt-get update` and I still got an error, although I can't recall vividly, but I'd try again; or better still, can I get a more windows-based command for those commands?

**Comment by ugochimobi** [comment]
> Hi,
> 
> it is a python project, so yes it can run on any platform. The general idea is to install the python dependencies and run the script. Maybe this link can help:
> 
> https://mothergeo-py.readthedocs.io/en/latest/development/how-to/venv-win.html
> 
> The instructions are more for a linux distribution. For the "Unable to fetch package" maybe you can do
> 
> `sudo apt-get update`
> 
> before. It might fix your problem.
> 
> Salut D063520

Oh, right, thanks!
Indeed, the instructions are more linux-based than windows; but I think I tried using that `sudo apt-get update` and I still got an error, although I can't recall vividly, but I'd try again; or better still, can I get a more windows-based command for those commands?

**Comment by D063520** [comment]
Hi,

the link I send:

https://mothergeo-py.readthedocs.io/en/latest/development/how-to/venv-win.html

 is to set up a virtual environment on windows.

This replaces the other commands. Please try to follow them

Salut
D063520

**Comment by ugochimobi** [comment]
> Hi,
> 
> the link I send:
> 
> https://mothergeo-py.readthedocs.io/en/latest/development/how-to/venv-win.html
> 
> is to set up a virtual environment on windows.
> 
> This replaces the other commands. Please try to follow them
> 
> Salut D063520

Many thanks, Dennis! \o/

**Comment by ugochimobi** [comment]
So, after a long run, I managed to set up the virtual environment, but when I run the command, for example, `python import_one.py Q1` it returns `Unable to create process using 'C:\Users\Myusername\AppData\Local\Programs\Python\Python310\python.exe import_one.py Q1'`
Any Idea of what I did wrong?

**Comment by D063520** [comment]
I guess this is an issue of python on Windows. Maybe this:

https://stackoverflow.com/questions/37220055/pip-fatal-error-in-launcher-unable-to-create-process-using

?

**Comment by ugochimobi** [comment]
> I guess this is an issue of python on Windows. Maybe this:
> 
> https://stackoverflow.com/questions/37220055/pip-fatal-error-in-launcher-unable-to-create-process-using
> 
> ?

That didn't solve it either, I tried running the pip upgrade `python -m pip install --upgrade pip` command but it didn't work.

**Comment by D063520** [comment]
Hi, this problem is not really related to the library, but to setting up python on a windows machine. I do not use windows, but this tutorial seams to be relatively complete:

https://phoenixnap.com/kb/how-to-install-python-3-windows

**Comment by ugochimobi** [comment]
Hi Dennis, I trust you're doing great :)
I managed to run it on my Desktop Computer that runs Windows 10 (64bit), but now I get an HTTP error, what do you think causes this? my network? I actually tried changing my internet connection but still returns an HTTP error, the full error below;
```
ERROR: Traceback (most recent call last):
  File "C:\Users\USER\venv\lib\site-packages\pywikibot\data\api.py", line 1489, in _http_request
    response = http.request(self.site, uri=uri,
  File "C:\Users\USER\venv\lib\site-packages\pywikibot\comms\http.py", line 232, in request
    r = fetch(baseuri, headers=headers, **kwargs)
  File "C:\Users\USER\venv\lib\site-packages\pywikibot\comms\http.py", line 393, in fetch
    callback(response)
  File "C:\Users\USER\venv\lib\site-packages\pywikibot\comms\http.py", line 277, in error_handling_callback
    raise ConnectionError(response)
ConnectionError: HTTPConnectionPool(host='http', port=80): Max retries exceeded with url: /w/api.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020ECF7B7550>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

Traceback (most recent call last):
  File "C:\Users\USER\WikibaseSync\import_one.py", line 9, in <module>
    wikibase_repo = wikibase.data_repository()
  File "C:\Users\USER\venv\lib\site-packages\pywikibot\site\_apisite.py", line 1151, in data_repository
    data = req.submit()
  File "C:\Users\USER\venv\lib\site-packages\pywikibot\data\api.py", line 2068, in submit
    cached_available = self._load_cache()
  File "C:\Users\USER\venv\lib\site-packages\pywikibot\data\api.py", line 2038, in _load_cache
    self._add_defaults()
  File "C:\Users\USER\venv\lib\site-packages\pywikibot\data\api.py", line 1250, in _add_defaults
    and self.site.mw_version >= '1.25wmf5'):
  File "C:\Users\USER\venv\lib\site-packages\pywikibot\site\_apisite.py", line 1111, in mw_version
    mw_ver = MediaWikiVersion(self.version())
  File "C:\Users\USER\venv\lib\site-packages\pywikibot\site\_apisite.py", line 1084, in version
    version = self.siteinfo.get('generator', expiry=1).split(' ')[1]
  File "C:\Users\USER\venv\lib\site-packages\pywikibot\site\_siteinfo.py", line 303, in get
    preloaded = self._get_general(key, expiry)
  File "C:\Users\USER\venv\lib\site-packages\pywikibot\site\_siteinfo.py", line 242, in _get_general
    default_info = self._get_siteinfo(props, expiry)
  File "C:\Users\USER\venv\lib\site-packages\pywikibot\site\_siteinfo.py", line 167, in _get_siteinfo
    data = request.submit()
  File "C:\Users\USER\venv\lib\site-packages\pywikibot\data\api.py", line 2070, in submit
    self._data = super().submit()
  File "C:\Users\USER\venv\lib\site-packages\pywikibot\data\api.py", line 1797, in submit
    response, use_get = self._http_request(use_get, uri, body, headers,
  File "C:\Users\USER\venv\lib\site-packages\pywikibot\data\api.py", line 1489, in _http_request
    response = http.request(self.site, uri=uri,
  File "C:\Users\USER\venv\lib\site-packages\pywikibot\comms\http.py", line 232, in request
    r = fetch(baseuri, headers=headers, **kwargs)
  File "C:\Users\USER\venv\lib\site-packages\pywikibot\comms\http.py", line 393, in fetch
    callback(response)
  File "C:\Users\USER\venv\lib\site-packages\pywikibot\comms\http.py", line 277, in error_handling_callback
    raise ConnectionError(response)
ConnectionError: HTTPConnectionPool(host='http', port=80): Max retries exceeded with url: /w/api.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020ECF7B7550>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
CRITICAL: Exiting due to uncaught exception <class 'ConnectionError'>
```

**Comment by D063520** [comment]
Hi!

On which address is your wikibase? What did you put in the config/application.config.ini under domain?

Salut
D063520

**Comment by ugochimobi** [comment]
I also tried changing them to `HTTPS` still returns same error

**Comment by D063520** [comment]
In:

https://github.com/the-qa-company/WikibaseSync/blob/master/config/application.config.ini

there is only the domain, not the protocol. Sop that part should be:

domain = gratisdata.miraheze.org
protocol = http

**Comment by ugochimobi** [comment]
Oh, can you imagine :), I missed that
Thank you very much!
Now it keeps retrying and returning a 200 Status code, and a WARNING: Non-JSON response received from server my:my for url.
I wonder why?

**Comment by D063520** [comment]
Hi,

the above problem was an error with the protocol. It should be https and not http.

I made an account on your wikibase. I run into anther problem which is that the code is not supporting latest mediawiki installations Was not aware of this. I put the changes in the pywikibot7 branch. 

The branch is configured in a way to be adapted to gratispedia. But I created a local account. Apparently "normal" users cannot create properties. Can you try with your admin account. Basically start from the branch and follow the instructions to change the user, password and bot.

Also I cannot test fully since one need a sparql endpoint and the sparql endpoint you indicated is only local. The sparql endpoint needs to be in sync with the wikibase otherwise it is not working.

Let me know!

Salut
D063520

**Comment by ugochimobi** [comment]
> Hi,
> 
> the above problem was an error with the protocol. It should be https and not http.
> 
> I made an account on your wikibase. I run into anther problem which is that the code is not supporting latest mediawiki installations Was not aware of this. I put the changes in the pywikibot7 branch.
> 
> The branch is configured in a way to be adapted to gratispedia. I created a new account called D063520. Apparently "normal" users cannot create properties. Can you try with your admin account? Basically start from the branch and follow the instructions to change the user, password and bot. Otherwise you can ping me at [dennis.diefenbach@the-qa-company.com](mailto:dennis.diefenbach@the-qa-company.com) if you can share an admin account an I can try to set it up.
> 
> Also I cannot test fully since one need a sparql endpoint. The sparql endpoint you indicated is only local. The sparql endpoint needs to be in sync with the wikibase otherwise it is not working.
> 
> Let me know!
> 
> Salut D063520
> 
> PS: when I edit with the configuration in the pywikibot7 branch I get:
> 
> permissiondenied: You do not have the permissions needed to carry out this action. [messages: [{'name': 'wikibase-api-permissiondenied', 'parameters': [], 'html': {'_': 'You do not have the permissions needed to carry out this action.'}}, {'name': 'namespaceprotected', 'parameters': ['Property', 'edit'], 'html': {'_': 'You do not have permission to edit pages in the **Property** namespace.'}}, {'name': 'namespaceprotected', 'parameters': ['Property', 'createpage'], 'html': {'_': 'You do not have permission to edit pages in the **Property** namespace.'}}, {'name': 'badaccess-groups', 'parameters': ['[[Gratisdata:Property creators|Property creators]], [[m:Special:MyLanguage/User groups#Administrators|Administrators]]', 2], 'html': {'_': 'The action you have requested is limited to users in one of the groups: [Property creators](/wiki/Gratisdata:Property_creators), [Administrators](https://meta.miraheze.org/wiki/Special:MyLanguage/User_groups#Administrators).'}}, {'name': 'namespaceprotected', 'parameters': ['Property', 'property-create'], 'html': {'*': 'You do not have permission to edit pages in the **Property** namespace.'}}]; help: See https://gratisdata.miraheze.org/w/api.php for API usage. Subscribe to the mediawiki-api-announce mailing list at <https://lists.wikimedia.org/postorius/lists/mediawiki-api-announce.lists.wikimedia.org/> for notice of API deprecations and breaking changes.]

Oh wow @D063520 thank you for taking time to try this out, I'm amazed \o/

Hum, the error you shared on the latter is definitely something related to permissions which is something I can do. So what if I give your account sysop permission? What do you think? I think that'd be preferrable?

I'd also try it on my own, but I'd give your account sysop permission.

**Comment by ugochimobi** [comment]
> Hi,
> 
> the above problem was an error with the protocol. It should be https and not http.
> 
> I made an account on your wikibase. I run into anther problem which is that the code is not supporting latest mediawiki installations Was not aware of this. I put the changes in the pywikibot7 branch.
> 
> The branch is configured in a way to be adapted to gratispedia. I created a new account called D063520. Apparently "normal" users cannot create properties. Can you try with your admin account? Basically start from the branch and follow the instructions to change the user, password and bot. Otherwise you can ping me at [dennis.diefenbach@the-qa-company.com](mailto:dennis.diefenbach@the-qa-company.com) if you can share an admin account an I can try to set it up.
> 
> Also I cannot test fully since one need a sparql endpoint. The sparql endpoint you indicated is only local. The sparql endpoint needs to be in sync with the wikibase otherwise it is not working.
> 
> Let me know!
> 
> Salut D063520
> 
> PS: when I edit with the configuration in the pywikibot7 branch I get:
> 
> permissiondenied: You do not have the permissions needed to carry out this action. [messages: [{'name': 'wikibase-api-permissiondenied', 'parameters': [], 'html': {'_': 'You do not have the permissions needed to carry out this action.'}}, {'name': 'namespaceprotected', 'parameters': ['Property', 'edit'], 'html': {'_': 'You do not have permission to edit pages in the **Property** namespace.'}}, {'name': 'namespaceprotected', 'parameters': ['Property', 'createpage'], 'html': {'_': 'You do not have permission to edit pages in the **Property** namespace.'}}, {'name': 'badaccess-groups', 'parameters': ['[[Gratisdata:Property creators|Property creators]], [[m:Special:MyLanguage/User groups#Administrators|Administrators]]', 2], 'html': {'_': 'The action you have requested is limited to users in one of the groups: [Property creators](/wiki/Gratisdata:Property_creators), [Administrators](https://meta.miraheze.org/wiki/Special:MyLanguage/User_groups#Administrators).'}}, {'name': 'namespaceprotected', 'parameters': ['Property', 'property-create'], 'html': {'*': 'You do not have permission to edit pages in the **Property** namespace.'}}]; help: See https://gratisdata.miraheze.org/w/api.php for API usage. Subscribe to the mediawiki-api-announce mailing list at <https://lists.wikimedia.org/postorius/lists/mediawiki-api-announce.lists.wikimedia.org/> for notice of API deprecations and breaking changes.]

Oh wow @D063520 thank you for taking time to try this out, I'm amazed \o/

Hum, the error you shared on the latter is definitely something related to permissions which is something I can do. So what if I give your account sysop permission? What do you think? I think that'd be preferrable?

I'd also try it on my own, but I'd give your account sysop permission.

**Comment by D063520** [comment]
This is fine for me. I promise I will not break anything. Can you give me an example entity you would like to import? There is still the problem with the SPARQL endpoint. Is there a public one?

**Comment by ugochimobi** [comment]
> This is fine for me. I promise I will not break anything. Can you give me an example entity you would like to import? There is still the problem with the SPARQL endpoint. Is there a public one?

Okay, nice, Hum, for the SPARQL endpoint, I think we'd have a little problem with that, cuz there's currently no endpoint for gratisdata yet, it won't work?

**Comment by ugochimobi** [comment]
> This is fine for me. I promise I will not break anything. Can you give me an example entity you would like to import? There is still the problem with the SPARQL endpoint. Is there a public one?

Okay, nice, Hum, for the SPARQL endpoint, I think we'd have a little problem with that, cuz there's currently no endpoint for gratisdata yet, it won't work?

**Comment by D063520** [comment]
No, without a SPARL endpoint it will not work. Maybe you can ping here once you set up one? You know that using the wikibase docker pipeline https://github.com/wmde/wikibase-release-pipeline you get everything for free?

**Comment by ugochimobi** [comment]
> No, without a SPARL endpoint it will not work. Maybe you can ping here once you set up one? You know that using the wikibase docker pipeline https://github.com/wmde/wikibase-release-pipeline you get everything for free?

I have no idea about that, but at least not now again, let me check it out.

PS: I hope I didn't give the wrong account sysop :)

**Comment by ugochimobi** [comment]
I couldn't figure out how to get a SPARQL endpoint with that? Lol

**Comment by D063520** [comment]
maybe this helps:

https://www.mediawiki.org/wiki/Wikibase/Docker

**Comment by ugochimobi** [comment]
I've reached out to Miraheze System Administrator (Gratisdata's host) they
just told me Docker wasn't use to install Wikibase over at miraheze....

**Comment by D063520** [comment]
Ah, you are not hosting it yourself .... then I think it will be difficult, I guess Miraheze is not offering all services related to wikibase.

**Comment by ugochimobi** [comment]
Wow, I can't believe this won't work out, so sad, anyway I'd talk to them about it as time goes on.

I am very grateful for your time that you've spent with me in this \o/

**Comment by ugochimobi** [comment]
Good evening Dennis, just a quick one; I was wondering since you were able to reach that part where the system denied your permission to create properties, why don't you try it again now that you have the permission let's see if it will work?

Kudos! \o/

**Comment by D063520** [comment]
Hi, I'm sure it will not work. In fact without the SPARQL endpoint he will probably create duplicated entities since he cannot see the once that were already inserted ....
Salut
D063520

**Comment by ugochimobi** [comment]
I so much appreciate the time you've spent with me here!
Thank you so much.

Can we probably chat in a private venue regarding Wikibase docker, I want you to advice/support me in setting up one, if you don't mind. Thanks! \o/
