### ISSUE TITLE
Could not setup the tool: Missing main.py and Incorrect username or password entered

### ISSUE THREAD

**Issue by phucty** [the-qa-company/WikibaseSync#3]
Hello, 

Thank you very much for making the tool available to use. 
It is very useful to reuse properties and items from Wikidata. 
I want to use the tool to create the external identifiers to Wikidata (like [https://linkedopendata.eu/wiki/Property:P1](https://linkedopendata.eu/wiki/Property:P1)) and the exiting Wikidata properties and schema items QID.
However, I got two problems during setup. 

1. I follow the setup guide in `README.md` but I could not find `main.py` in step 4.

2. Skip the main.py editing. I continue the remaining steps and I got an incorrect username or password entered problem when running the `import_one.py` and `import_list.py`.

`Traceback (most recent call last):
  File "/Users/phucnguyen/Library/Application Support/JetBrains/Toolbox/apps/PyCharm-P/ch-0/212.5457.59/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydevd_bundle/pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<input>", line 1, in <module>
  File "/Users/phucnguyen/anaconda3/envs/wikicom/lib/python3.10/site-packages/pywikibot/tools/__init__.py", line 1478, in wrapper
    return obj(*__args, **__kw)
  File "/Users/phucnguyen/anaconda3/envs/wikicom/lib/python3.10/site-packages/pywikibot/site/_apisite.py", line 404, in login
    if login_manager.login(retry=True, autocreate=autocreate):
  File "/Users/phucnguyen/anaconda3/envs/wikicom/lib/python3.10/site-packages/pywikibot/login.py", line 312, in login
    self.login_to_site()
  File "/Users/phucnguyen/anaconda3/envs/wikicom/lib/python3.10/site-packages/pywikibot/data/api.py", line 2969, in login_to_site
    raise CaptchaError('Captcha encountered which cannot be '
pywikibot.exceptions.CaptchaError: Captcha encountered which cannot be handled:
{'result': 'Failed', 'reason': 'Incorrect username or password entered. Please try again.'}`

I already tried two difference ways of input as Wikibase suggested:
```
Bot password created
Jump to navigationJump to search
The bot password for bot name "wikicom" of user "Admin" was created.

The new password to log in with Admin@wikicom is rohoeql13q36lq3q04ecekdsj9ktqgvk. Please record this for future reference.
(For old bots which require the login name to be the same as the eventual username, you can also use Admin as username and wikicom@rohoeql13q36lq3q04ecekdsj9ktqgvk as password.)
Return to Special:BotPasswords.

```

Could you please help me resolve the problems?

Thank you very much for your time and support.
Best regards,

Phuc

**Comment by D063520** [comment]
Hi,

thank you for trying out the library. We are using it a lot at linkedopendata.eu, but you might be the first trying it out outside this project!

About your points

1. true the main.py does not exists. I just cloned the project and followed the instruction without that part and it worked. I could import an entity. I changed the README now.
2. The second problem, as far as I understand, means that the pywikibot is not able to log in. I found this answer in the mailing list:
https://lists.wikimedia.org/hyperkitty/list/wikitech-l@lists.wikimedia.org/thread/TDNSBETBSZXF36YIGXIVDHEAI3UGC35I/ 

>The relevant portion is {'result': 'Failed', 'reason':
>'Incorrect username
>or password entered. Please try again.'}.

>You should not be using the same password that is used to log in to the web
>UI. For a BotPassword, see the configuration steps at
>https://www.mediawiki.org/wiki/Manual:Pywikibot/BotPasswords.

Did you use the bot password?

**Comment by D063520** [comment]
can you try in user-password.py with

(u'Admin', BotPassword(u'wikicom', u'rohoeql13q36lq3q04ecekdsj9ktqgvk'))

or with

(u'wikicom', BotPassword(u'wikicom', u'rohoeql13q36lq3q04ecekdsj9ktqgvk'))

We called the bot and the username the same. So I'm a bit confused here.

**Comment by phucty** [comment]
Thank @D063520 very much for your time and support. 

Finally, I can run the lib now with your suggestions. 

The following are some modifications to run WikibaseSync scripts. It might be useful for others.
I follow the new docker of Wikibase so there are some difference than the old setting. 

- Adding the config2 setting (in import_all_changes) to import_list.py and import_one.py --> fix the login error of wikibase.
```
from pywikibot import config2
import configparser
app_config = configparser.ConfigParser()
app_config.read('config/application.config.ini')


family = 'my'
mylang = 'my'
familyfile=os.path.relpath("./config/my_family.py")
if not os.path.isfile(familyfile):
  print ("family file %s is missing" % (familyfile))
config2.register_family_file(family, familyfile)
config2.password_file = "user-password.py"
config2.usernames['my']['my'] = app_config.get('wikibase', 'user')
```

- user-password.py:
`('Admin', BotPassword('wikicom', 'n744sap4mbde1o67mtderuhof8eobk5t'))`

- config:
```
user = Admin
sparqlEndPoint = http://localhost:8834/proxy/wdqs/bigdata/namespace/wdq/sparql
domain = localhost
protocol = http
apiUrl= http://localhost/w/api.php
entityUri=http://localhost/entity
propertyUri=http://localhost/prop
```

- fix bugs during QID import 
  + Label and description for language code en can not have the same value. Add "Description: " as prefix of desc value.

**Comment by D063520** [comment]
Hi cool,

could you make a pull request with the changes you needed? Also, what was the right alternative:

(u'Admin', BotPassword(u'wikicom', u'rohoeql13q36lq3q04ecekdsj9ktqgvk'))

or with

(u'wikicom', BotPassword(u'wikicom', u'rohoeql13q36lq3q04ecekdsj9ktqgvk'))

like this I can maybe change the documentation.

Salut
D063520

**Comment by D063520** [comment]
Hi, thank you! Based on your feedback I already made two small changes .... 
https://github.com/the-qa-company/WikibaseSync/commit/13e648b5f096e84ae12452f2e88c953982aa9b8e
https://github.com/the-qa-company/WikibaseSync/commit/55027128bfa268aae203f0dac7c9cd5396afa979
Salut D063520

**Comment by phucty** [comment]
Hi Dennis,
Great thanks. 

Another bug of duplicate importing. 
https://github.com/the-qa-company/WikibaseSync/blob/55027128bfa268aae203f0dac7c9cd5396afa979/util/util.py#L921

I change "WikidataUpdater" to my account name "Admin" to avoid property constraint duplications.

**Comment by D063520** [comment]
I changed it ...

**Comment by phucty** [comment]
Missing claim errors

Cause:
https://github.com/the-qa-company/WikibaseSync/blob/6d04d6a0990443aee163de8c5775808a592d40a6/util/util.py#L561

Fix:
`item = pywikibot.PropertyPage(self.wikidata_repo, wikidata_objectId) `

**Comment by phucty** [comment]
Hi @D063520,

I am refactoring source code of Wikibase tool. So, please ignore the reported bugs. I will pull new requests (tag @D063520 at the end) after testing on my test Wikibase instance. 

ヽ(´ー`)ﾉ｡o○Thanks.
