### ISSUE TITLE
modification-failed: Label and description for language code sv can not have the same value.

### ISSUE THREAD

**Issue by D063520** [the-qa-company/WikibaseSync#6]
this happens at import time because in Wikidata some properties and entities have the same label and description. This is forbidden in a Wikibase. Opened an issue to ask why this is happening:

https://phabricator.wikimedia.org/T297813

Full stack trace

Error probably property or item already existing  Edit to page [[my:Property:-1]] failed:
modification-failed: Label and description for language code sv can not have the same value.
[messages: [{'name': 'wikibase-validator-label-equals-description', 'parameters': ['sv'], 'html': {'*': 'Label and description for language code sv can not have the same value.'}}];
 help: See http://localhost/w/api.php for API usage. Subscribe to the mediawiki-api-announce mailing list at &lt;https://lists.wikimedia.org/mailman/listinfo/mediawiki-api-announce&gt; for notice of API deprecations and breaking changes.]
Change Entity  Q11573
Import Entity Q11573 from Wikidata
Traceback (most recent call last):
  File "import_one.py", line 27, in <module>
    wikibase_importer.change_item(wikidata_item, wikibase_repo, True)
  File "/Users/Dennis/Downloads/WikibaseSync/util/util.py", line 1078, in change_item
    self.changeClaims(wikidata_item, wikibase_item)
  File "/Users/Dennis/Downloads/WikibaseSync/util/util.py", line 992, in changeClaims
    claim = self.translateClaim(wikidata_claim.get('mainsnak'))
  File "/Users/Dennis/Downloads/WikibaseSync/util/util.py", line 680, in translateClaim
    claim = pywikibot.page.Claim(self.wikibase_repo, self.id.get_id(wikidata_propertyId),
  File "/Users/Dennis/Downloads/WikibaseSync/util/IdSparql.py", line 52, in get_id
    return self.mapProperty[id]
KeyError: 'P2044'

**Comment by mezez** [comment]
Updates have been made to skip labels(languages) that contain the same value for label and description
